import type { Metadata } from "next";
import { Inter, Kantumruy_Pro } from "next/font/google";
import "./globals.css";

const getInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const getKantumruy = Kantumruy_Pro({
  variable: "--font-KantumruyPro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getInter.variable} ${getKantumruy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
